### ISSUE TITLE
Crash in client

### ISSUE THREAD

**Issue by williamleven** [Gurgy/stalkIT#4]
Log från klient efter att datorn varit i sleep-mode
```
ELIT has arrived at the Hubb
Runvik has arrived at the Hubb
Nooz has arrived at the Hubb
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x401c90]

goroutine 19 [running]:
panic(0x59d7c0, 0xc82000a130)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
main.notifier()
	/home/gurgy/Documents/Git/Go/src/stalkIT/client/notifier.go:37 +0x5a0
created by main.main
	/home/gurgy/Documents/Git/Go/src/stalkIT/client/main.go:5 +0x2b
```

**Comment by williamleven** [comment]
@Sephecure Något som du vet hur det gick till?

**Comment by hulthe** [comment]
Verkar som att felet händer här:
`output := message.User.Nick`
Antagligen så lämnar buffern ifrån sig en tom sträng när anslutningen har brutits, som json.Unmarshal sedan ger tillbaka som ett nil Message-objekt

**Comment by hulthe** [comment]
@Gurgy Vi måste hantera tappade anslutningar för klienten på ett snyggt sätt, lite skumt att buffern inte ger ifrån sig något fel...
`data, err := bufio.NewReader(conn).ReadString('\n')`

**Comment by williamleven** [comment]
Antar att det är message som blir nil? borde väll bara kunna lägga en check på det?

ja, verklingen går det inte att göra något test på `net.Conn` (våran `conn`)?
